[package]
name = "neon-helloworld"
version = "0.1.0"
authors = ["Cameron Taggart <cameron.taggart@gmail.com>"]
license = "MIT"
build = "build.rs"

[lib]
name = "neon_helloworld"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.1.19"

[dependencies]
neon = "0.1.19"
